[workspace]
members = [
    "macros",
]

[package]
name = "emu-utils"
version = "0.0.0"
edition = "2021"
publish = false

[features]
std = []

[dependencies]
cfg-if = "1.0"
emu-utils-macros = { path = "macros" }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"